import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>
          Emergency Food and Shelter Program Project With Georgia Tech
        </h1>

        <div className={styles.description}>
          <h2 className={styles.card}>
            About This Project
          </h2>
          The Emergency Food and Shelter Program is a federal grant that provides funds to agencies for emergency financial assistance for individuals and families in crisis. United Way of Greater Atlanta administers this grant in eight metro counties.
          This application tracks the recipients of funds for grant administers and to provide an interface for logging distributions and providing analytics about previous funding records.
        </div>

        <table className={styles.styledTable}>
          <thead>
            <tr>
              <th>Name</th>
              <th>Role</th>
              <th>Goal</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{'Marium Ali'}</td>
              <td>{'Front End Engineer'}</td>
              <td>{'Develop a working and easy to use MVP for client to be able to use'}</td>
            </tr>
            <tr className={styles.activeRow}>
              <td>Melissa</td>
              <td>5150</td>
            </tr>
          </tbody>
        </table>

        <div className={styles.description}>
          <h2 className={styles.card}>
            Goals of this Project
          </h2>

            <li>Provide an online form to submit funding requests</li>
            <li>Maintain a database of all previous funding grants</li>
            <li>Provide an interface to view previous grants</li>
            <li>Enable administers to view the current status of funding</li>

        </div>
      </main>
    </>
  )
}
